version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: podcast_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: podcast_db
      MYSQL_USER: podcast_user
      MYSQL_PASSWORD: 123456789
    ports:
      - "5306:3306"
    volumes:
      - podcast_db_data:/var/lib/mysql
    networks:
      - podcast_net

  app:
    container_name: podcast_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DOCKER_ENV: "true"
      DB_HOST: trolley.proxy.rlwy.net
      DB_PORT: 53938
      DB_USER: root
      DB_PASSWORD: JmvcmOdpbKIXqZAbBhzPkfWGLqHeospE
      DB_NAME: railway
      JWT_SECRET: super_secret_123456
      SUPABASE_URL: https://iyqehfbrqwwofajeyudh.supabase.co
      #SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5cWVoZmJycXd3b2ZhamV5dWRoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTI1MTc0OSwiZXhwIjoyMDc0ODI3NzQ5fQ.9fAGIjuG2jm0-Bgm1F3GnYqafKx7bjW2N04PFI0Y2TI
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5cWVoZmJycXd3b2ZhamV5dWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNTE3NDksImV4cCI6MjA3NDgyNzc0OX0.XJry21DBi73i9FCXeYnLZsv-bE5gJJs4qKM_Q-lnZII

      GEMINI_API_KEY: AIzaSyCeGZiWJ6_Ynysbwt5-32VRStPTGs1Iwyw
      API_BASE_URL: https://apipodcastt.onrender.com
      GOOGLE_APPLICATION_CREDENTIALS: /root/credentials/google-credentials.json
    networks:
      - podcast_net

volumes:
  podcast_db_data: {}

networks:
  podcast_net:
